#!/bin/sh

# Change your keymap:
xmodmap "/home/arian/.Xmodmap"

which fbautostart > /dev/null
if [ $? -eq 0 ]; then
    fbautostart
fi

nm-applet &
pasystray &
cbatticon &
unclutter -idle 2 &
/home/arian/Documents/code/git_hub/nixian/installers/cortile &

exec fluxbox
